import type { Product } from '@/types/product'

/**
 * بيانات المنتجات (Mock).
 * عند ربط الـ Flask API، يُستبدل هذا الملف بخدمة الـ API دون تغيير الـ UI.
 */

const img = (seed: string, w = 800, h = 800) =>
  `https://images.unsplash.com/${seed}?auto=format&fit=crop&w=${w}&h=${h}&q=70`

export const products: Product[] = [
  {
    id: 'p-001',
    slug: 'luminous-glow-serum',
    name: 'سيروم التوهج المضيء',
    price: 890,
    compareAtPrice: 1140,
    description:
      'سيروم خفيف بفيتامين C والنياسيناميد يوحّد لون البشرة ويعزز الإشراقة لتوهج طبيعي من الداخل.',
    benefits: ['يضيء البشرة الباهتة', 'يوحّد لون البشرة', 'يعزز الترطيب', 'ينعّم الخطوط الدقيقة'],
    ingredients: ['فيتامين C 10%', 'نياسيناميد 5%', 'حمض الهيالورونيك', 'حمض الفروليك'],
    howToUse: ['ضعي 3-4 قطرات على بشرة نظيفة كل صباح.', 'تابعي بمرطب وواقٍ من الشمس.'],
    suitableFor: ['جميع أنواع البشرة', 'البشرة الباهتة أو المتعبة', 'اللون غير الموحد'],
    faqs: [
      { question: 'هل يمكن استخدامه مع الريتينول؟', answer: 'ننصح بالتناوب بين الصباح والمساء لتجنب التهيج.' },
      { question: 'هل هو خالٍ من العطور؟', answer: 'نعم، سيروم التوهج مصنوع بدون إضافة عطور.' },
    ],
    category: { id: 'cat-skin', slug: 'skin-care', name: 'العناية بالبشرة' },
    variants: [
      { id: 'v-001', name: '30ml', sku: 'SL-GLOW-30', price: 890, compareAtPrice: 1140, stock: 24 },
      { id: 'v-002', name: '50ml', sku: 'SL-GLOW-50', price: 1290, compareAtPrice: 1540, stock: 12 },
    ],
    images: [
      { id: 'i-1', url: img('photo-1570172619644-dfd03ed5d881'), alt: 'زجاجة سيروم التوهج المضيء' },
      { id: 'i-2', url: img('photo-1620916566398-39f1143ab7be'), alt: 'تطبيق نسيج السيروم' },
    ],
    rating: 4.8,
    reviewCount: 214,
    inventoryStatus: 'in-stock',
    stock: 24,
    tags: ['serum', 'vitamin c', 'glow'],
    isBestseller: true,
    isNew: false,
    featured: true,
    created_at: '2026-05-01',
  },
  {
    id: 'p-002',
    slug: 'radiant-cream-cleanser',
    name: 'منظف كريمي مشع',
    price: 420,
    description:
      'منظف كريمي لطيف خالٍ من الكبريتات يزيل الشوائب دون تجريد حاجز البشرة الطبيعي.',
    benefits: ['يزيل المكياج وواقي الشمس', 'يحافظ على حاجز الرطوبة', 'يهدّئ التهيج'],
    ingredients: ['جلسرين', 'بانثينول', 'ألوفيرا', 'منظفات لطيفة'],
    howToUse: ['دلّكي على بشرة رطبة.', 'اشطفي بماء فاتر. استخدميه صباحاً ومساءً.'],
    suitableFor: ['البشرة الحساسة', 'البشرة الجافة', 'الاستخدام اليومي'],
    faqs: [
      { question: 'هل هو آمن للبشرة الحساسة؟', answer: 'نعم، خالٍ من العطور ومختبر من أطباء الجلدية.' },
    ],
    category: { id: 'cat-skin', slug: 'skin-care', name: 'العناية بالبشرة' },
    variants: [{ id: 'v-003', name: '150ml', sku: 'SL-CLEAN-150', price: 420, stock: 60 }],
    images: [
      { id: 'i-1', url: img('photo-1556228720-195a672e8a03'), alt: 'أنبوب المنظف الكريمي المشع' },
    ],
    rating: 4.7,
    reviewCount: 168,
    inventoryStatus: 'in-stock',
    stock: 60,
    tags: ['cleanser', 'gentle', 'sensitive'],
    isBestseller: true,
    isNew: false,
    created_at: '2026-04-10',
  },
  {
    id: 'p-003',
    slug: 'hydro-plump-moisturizer',
    name: 'مرطب الترطيب الكثيف',
    price: 650,
    compareAtPrice: 780,
    description:
      'مرطب غني سريع الامتصاص بحمض الهيالورونيك والسيراميد لترطيب يدوم 72 ساعة.',
    benefits: ['ترطيب 72 ساعة', 'يقوّي حاجز البشرة', 'لمسة نهائية غير دهنية'],
    ingredients: ['حمض الهيالورونيك', 'سيراميد', 'سكوالين', 'فيتامين E'],
    howToUse: ['ضعي كمية بحجم حبة البازلاء صباحاً ومساءً فوق السيروم.'],
    suitableFor: ['البشرة الجافة', 'البشرة العادية', 'البشرة المجففة'],
    faqs: [
      { question: 'هل يمكن استخدامه تحت المكياج؟', answer: 'نعم، يمتص بسرعة ويُطبق بسهولة فوقه.' },
    ],
    category: { id: 'cat-skin', slug: 'skin-care', name: 'العناية بالبشرة' },
    variants: [{ id: 'v-004', name: '50ml', sku: 'SL-HYDRO-50', price: 650, compareAtPrice: 780, stock: 18 }],
    images: [{ id: 'i-1', url: img('photo-1620916566398-39f1143ab7be'), alt: 'برطمان مرطب الترطيب الكثيف' }],
    rating: 4.6,
    reviewCount: 97,
    inventoryStatus: 'low-stock',
    stock: 5,
    tags: ['moisturizer', 'hydration', 'barrier'],
    isBestseller: false,
    isNew: true,
    featured: true,
    created_at: '2026-06-20',
  },
  {
    id: 'p-004',
    slug: 'silken-hair-mask',
    name: 'ماسك الشعر الحريري',
    price: 540,
    description:
      'ماسك كيراتين مصلّح يعيد المرونة ويترك الشعر ناعماً وأملس وخالياً من التجعد.',
    benefits: ['يصلّح التلف', 'يقلل التجعد', 'يضيف لمعاناً ونعومة'],
    ingredients: ['كيراتين', 'زيت الأرغان', 'زبدة الشيا', 'بانثينول'],
    howToUse: ['ضعيه على شعر رطب من الأطوال المتوسطة.', 'اتركيه 5-10 دقائق ثم اشطفي.'],
    suitableFor: ['الشعر الجاف', 'الشعر المصبوغ', 'الشعر التالف'],
    faqs: [
      { question: 'كم مرة يجب أن أستخدمه؟', answer: 'من 1-2 مرات أسبوعياً لأفضل النتائج.' },
    ],
    category: { id: 'cat-hair', slug: 'hair-care', name: 'العناية بالشعر' },
    variants: [{ id: 'v-005', name: '250ml', sku: 'SL-MASK-250', price: 540, stock: 32 }],
    images: [{ id: 'i-1', url: img('photo-1522337660859-02fbefca4702'), alt: 'برطمان ماسك الشعر الحريري' }],
    rating: 4.9,
    reviewCount: 143,
    inventoryStatus: 'in-stock',
    stock: 32,
    tags: ['hair', 'mask', 'keratin'],
    isBestseller: true,
    isNew: false,
    created_at: '2026-03-15',
  },
  {
    id: 'p-005',
    slug: 'eye-bright-cream',
    name: 'كريم العين المشرق',
    price: 720,
    compareAtPrice: 860,
    description:
      'كريم عين منعش بتركيبة الكافيين يزيل الانتفاخ، يضيء الهالات الداكنة وينعّم الخطوط الدقيقة.',
    benefits: ['يقلل الانتفاخ', 'يضيء الهالات الداكنة', 'ينعّم الخطوط الدقيقة'],
    ingredients: ['كافيين', 'ببتيدات', 'فيتامين K', 'حمض الهيالورونيك'],
    howToUse: ['ربّتي بلطف كمية بحجم حبة الأرز تحت العينين صباحاً ومساءً.'],
    suitableFor: ['العيون المنتفخة', 'الهالات الداكنة', 'الخطوط الدقيقة'],
    faqs: [
      { question: 'هل هو مختبر من أطباء العيون؟', answer: 'نعم، آمن لمنطقة العين الحساسة.' },
    ],
    category: { id: 'cat-eye', slug: 'eye-care', name: 'العناية بالعين' },
    variants: [{ id: 'v-006', name: '15ml', sku: 'SL-EYE-15', price: 720, compareAtPrice: 860, stock: 20 }],
    images: [{ id: 'i-1', url: img('photo-1616394584738-fc6e612e71b9'), alt: 'أنبوب كريم العين المشرق' }],
    rating: 4.7,
    reviewCount: 88,
    inventoryStatus: 'in-stock',
    stock: 20,
    tags: ['eye', 'caffeine', 'brightening'],
    isBestseller: true,
    isNew: false,
    created_at: '2026-02-01',
  },
  {
    id: 'p-006',
    slug: 'nail-strength-elixir',
    name: 'إكسير تقوية الأظافر',
    price: 280,
    description:
      'زيت أظافر وبشرة محيطية غني بالفيتامينات يقوّي الأظافر وينعّم الجلد المحيط.',
    benefits: ['يقوّي الأظافر', 'ينعّم الجلد المحيط', 'يضيف لمعاناً صحياً'],
    ingredients: ['فيتامين E', 'زيت الجوجوبا', 'بيوتين', 'زيت اللوز'],
    howToUse: ['دلّكي بضع قطرات على الأظافر والجلد المحيط يومياً.'],
    suitableFor: ['الأظافر الضعيفة', 'الأظافر الهشة', 'الجلد المحيط الجاف'],
    faqs: [{ question: 'هل يمكن استخدامه مع طلاء الجل؟', answer: 'نعم، ضعيه على الجلد المحيط والأظافر.' }],
    category: { id: 'cat-nail', slug: 'nail-care', name: 'العناية بالأظافر' },
    variants: [{ id: 'v-007', name: '15ml', sku: 'SL-NAIL-15', price: 280, stock: 45 }],
    images: [{ id: 'i-1', url: img('photo-1604654894610-df63bc536371'), alt: 'قطارة إكسير تقوية الأظافر' }],
    rating: 4.5,
    reviewCount: 54,
    inventoryStatus: 'in-stock',
    stock: 45,
    tags: ['nail', 'strengthen', 'cuticle'],
    isBestseller: false,
    isNew: false,
    created_at: '2026-01-20',
  },
  {
    id: 'p-007',
    slug: 'gentle-kids-balm',
    name: 'بلسم الأطفال اللطيف',
    price: 320,
    description:
      'بلسم هيبوالرجينيك مختبر من أطباء الجلدية يهدّئ ويحمي بشرة الأطفال الحساسة.',
    benefits: ['مهدّئ', 'هيبوالرجينيك', 'خالٍ من العطور'],
    ingredients: ['آذريون', 'زبدة الشيا', 'أكسيد الزنك', 'بابونج'],
    howToUse: ['ضعيه على بشرة نظيفة وجافة عند الحاجة. أعيدي وضعه بعد الاستحمام.'],
    suitableFor: ['الرضّع', 'الأطفال الصغار', 'البشرة الحساسة'],
    faqs: [{ question: 'هل هو آمن لعدم التسبب بالدموع؟', answer: 'نعم، لطيف ولا يلسع البشرة الحساسة.' }],
    category: { id: 'cat-kids', slug: 'kids-care', name: 'عناية الأطفال' },
    variants: [{ id: 'v-008', name: '100ml', sku: 'SL-KIDS-100', price: 320, stock: 70 }],
    images: [{ id: 'i-1', url: img('photo-1519689680058-324335c77eba'), alt: 'علبة بلسم الأطفال اللطيف' }],
    rating: 4.8,
    reviewCount: 39,
    inventoryStatus: 'in-stock',
    stock: 70,
    tags: ['kids', 'balm', 'soothing'],
    isBestseller: false,
    isNew: true,
    created_at: '2026-07-01',
  },
  {
    id: 'p-008',
    slug: 'dew-drop-toner',
    name: 'تونر قطرات الندى',
    price: 390,
    description:
      'تونر مرطب خالٍ من الكحول بالشاي الأخضر وماء الورد لتجهيز البشرة وتنقية المسام.',
    benefits: ['ينقّي المسام', 'يوازن درجة الحموضة', 'يرطب فوراً'],
    ingredients: ['مستخلص الشاي الأخضر', 'ماء الورد', 'حمض الهيالورونيك'],
    howToUse: ['امسحي به على بشرة نظيفة بقطعة قطن أو رشيه مباشرة.'],
    suitableFor: ['جميع أنواع البشرة', 'البشرة الدهنية', 'البشرة الباهتة'],
    faqs: [{ question: 'هل يحتوي على كحول؟', answer: 'لا، خالٍ تماماً من الكحول.' }],
    category: { id: 'cat-skin', slug: 'skin-care', name: 'العناية بالبشرة' },
    variants: [{ id: 'v-009', name: '200ml', sku: 'SL-TONER-200', price: 390, stock: 40 }],
    images: [{ id: 'i-1', url: img('photo-1608248543803-ba4f8c70ae0b'), alt: 'زجاجة تونر قطرات الندى' }],
    rating: 4.6,
    reviewCount: 72,
    inventoryStatus: 'in-stock',
    stock: 40,
    tags: ['toner', 'hydrating', 'pores'],
    isBestseller: false,
    isNew: false,
    created_at: '2026-05-10',
  },
  {
    id: 'p-009',
    slug: 'velvet-body-oil',
    name: 'زيت الجسم المخملي',
    price: 480,
    description:
      'زيت جسم سريع الامتصاص يمنح إشراقة بالسكوالين ونواة المشمش لبشرة ناعمة وحريرية.',
    benefits: ['إشراقة فورية', 'تغذية عميقة', 'امتصاص سريع'],
    ingredients: ['سكوالين', 'زيت نواة المشمش', 'فيتامين E', 'جوجوبا'],
    howToUse: ['دلّكيه على بشرة رطبة بعد الاستحمام.'],
    suitableFor: ['البشرة الجافة', 'كامل الجسم', 'عشاق الإشراقة'],
    faqs: [{ question: 'هل يترك بقعاً على الملابس؟', answer: 'لا، يمتص بسرعة دون بقايا.' }],
    category: { id: 'cat-skin', slug: 'skin-care', name: 'العناية بالبشرة' },
    variants: [{ id: 'v-010', name: '100ml', sku: 'SL-BODYOIL-100', price: 480, stock: 26 }],
    images: [{ id: 'i-1', url: img('photo-1620916566398-39f1143ab7be'), alt: 'زجاجة زيت الجسم المخملي' }],
    rating: 4.7,
    reviewCount: 61,
    inventoryStatus: 'low-stock',
    stock: 4,
    tags: ['body', 'oil', 'glow'],
    isBestseller: false,
    isNew: true,
    created_at: '2026-06-05',
  },
]
