"""admin role

Revision ID: 7381b63ef5b8
Revises: e4b7c9a1f023
Create Date: 2026-10-02 14:27:51.882193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7381b63ef5b8'
down_revision = 'e4b7c9a1f023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        # server_default ضروري: SQLite يرفض إضافة عمود NOT NULL بلا قيمة
        # افتراضية — حتى على جدول فارغ.
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_product_id'))

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
